### ISSUE TITLE
Add UTSC timetable dataset

### ISSUE THREAD

**Issue by galacticglum** [sqrl-planner/gator-app#1]
Add support for UTSC campus in timetable. Needs to implement a scraper for the [UTSC timetable planner](https://www.utsc.utoronto.ca/registrar/timetable). 

See [``utsg.py``](https://github.com/sqrl-planner/sqrl-server/blob/204e9fbfb75a71f558a8c9d82c4988922f50c75b/sqrl/data/sources/utsg.py) for an example implementation of a timetable dataset source.

**Comment by joelebutler** [comment]
I was able to start on this a little bit, but I won't have time to finish it and couldn't figure out how to do testing with it. If anyone is interested in picking up off the progress I made, it's at https://github.com/joelebutler/gator/commit/6708ba9bdd1c25ab3e2283cecfadbea058311486. I left comments for the different reasons I removed certain things but left the actual content in it case it does need to be used.
